export const ROUTES = {
  main: "/overview",
  users: "/overview/users",
  bookings: "/overview/bookings",
  clients: "/overview/clients",
  payments: "/overview/payments",
  tours: "/overview/tours",
  reports: "/overview/reports",
  logout: "/overview/logout",
  calendar: "/overview/calendar",
  chat: "/overview/chat",
  Kanban: "/overview/kanban",
  profile: "/overview/profile",
  darkTheme: "/overview/darkTheme",
  expenses: "/overview/expenses",
  account: "/overview/account/general",
  settings: "/overview/settings",
};