(self.webpackChunk_N_E=self.webpackChunk_N_E||[]).push([[5701],{13477:function(e,i,t){(window.__NEXT_P=window.__NEXT_P||[]).push(["/docs/installation/using-postcss",function(){return t(95524)}])},88943:function(e,i,t){"use strict";t.d(i,{_:function(){return n}});var s=t(85893),l=t(10640);function n(e){let{description:i,href:t,label:n}=e;return(0,s.jsxs)("p",{className:"flex flex-wrap sm:flex-nowrap lg:flex-wrap xl:flex-nowrap items-center py-6 px-4 sm:p-6 lg:p-10 ring-1 ring-slate-900/5 shadow rounded-lg dark:bg-slate-800 dark:shadow-none dark:ring-0 dark:highlight-white/5",children:[(0,s.jsxs)("span",{className:"flex-auto flex items-start mb-8 sm:mb-0 lg:mb-8 xl:mb-0",children:[(0,s.jsx)("svg",{viewBox:"0 -4 16 24",fill:"currentColor",className:"flex-none w-4 h-6 mr-4","aria-hidden":"true",children:(0,s.jsx)("path",{fillRule:"evenodd",clipRule:"evenodd",d:"M4 0a4 4 0 0 0-4 4v8a4 4 0 0 0 4 4h8a4 4 0 0 0 4-4V4a4 4 0 0 0-4-4H4Zm5 5a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM7 7a2 2 0 0 1 2 2v2a1 1 0 1 1-2 0V7Z"})}),(0,s.jsx)("span",{className:"flex-auto text-sm leading-6 text-slate-600 xl:max-w-2xl dark:text-slate-400",children:i})]}),(0,s.jsx)("span",{className:"flex-none flex justify-center w-full sm:w-auto sm:ml-6 md:ml-8 lg:w-full lg:ml-0 xl:w-auto xl:ml-8",children:(0,s.jsx)(l.z,{href:t,darkColor:"sky",children:n})})]})}},95524:function(e,i,t){"use strict";t.r(i),t.d(i,{__N_SSG:function(){return d},default:function(){return c}});var s=t(85893),l=t(72788),n=t(15236),a=t(88943),o=t(39897);let r=[{title:"Install Tailwind CSS",body:()=>(0,s.jsxs)("p",{children:["Install ",(0,s.jsx)("code",{children:"tailwindcss"})," and its peer dependencies via npm, and create your"," ",(0,s.jsx)("code",{children:"tailwind.config.js"})," file."]}),code:{name:"Terminal",lang:"terminal",code:"npm install -D tailwindcss postcss autoprefixer\nnpx tailwindcss init"}},{title:"Add Tailwind to your PostCSS configuration",body:()=>(0,s.jsxs)("p",{children:["Add ",(0,s.jsx)("code",{children:"tailwindcss"})," and ",(0,s.jsx)("code",{children:"autoprefixer"})," to your"," ",(0,s.jsx)("code",{children:"postcss.config.js"})," file, or wherever PostCSS is configured in your project."]}),code:{name:"postcss.config.js",lang:"js",code:`  module.exports = {
    plugins: {
>     tailwindcss: {},
>     autoprefixer: {},
    }
  }`}},{title:"Configure your template paths",body:()=>(0,s.jsxs)("p",{children:["Add the paths to all of your template files in your ",(0,s.jsx)("code",{children:"tailwind.config.js"})," file."]}),code:{name:"tailwind.config.js",lang:"js",code:`  /** @type {import('tailwindcss').Config} */
  module.exports = {
>   content: ["./src/**/*.{html,js}"],
    theme: {
      extend: {},
    },
    plugins: [],
  }`}},{title:"Add the Tailwind directives to your CSS",body:()=>(0,s.jsxs)("p",{children:["Add the ",(0,s.jsx)("code",{children:"@tailwind"})," directives for each of Tailwind’s layers to your main CSS file."]}),code:{name:"main.css",lang:"css",code:"@tailwind base;\n@tailwind components;\n@tailwind utilities;"}},{title:"Start your build process",body:()=>(0,s.jsxs)("p",{children:["Run your build process with ",(0,s.jsx)("code",{children:"npm run dev"})," or whatever command is configured in your ",(0,s.jsx)("code",{children:"package.json"})," file."]}),code:{name:"Terminal",lang:"terminal",code:"npm run dev"}},{title:"Start using Tailwind in your HTML",body:()=>(0,s.jsxs)("p",{children:["Make sure your compiled CSS is included in the ",(0,s.jsx)("code",{children:"<head>"})," ",(0,s.jsx)("em",{children:"(your framework might handle this for you)"}),", then start using Tailwind’s utility classes to style your content."]}),code:{name:"index.html",lang:"html",code:`  <!doctype html>
  <html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/dist/main.css" rel="stylesheet">
  </head>
  <body>
>   <h1 class="text-3xl font-bold underline">
>     Hello world!
>   </h1>
  </body>
  </html>`}}];var d=!0;function c(e){let{code:i}=e;return(0,s.jsxs)(n.l,{children:[(0,s.jsxs)("div",{id:"content-wrapper",className:"relative z-10 max-w-3xl mb-16 prose prose-slate dark:prose-dark",children:[(0,s.jsx)("h3",{className:"sr-only",children:"Installing Tailwind CSS as a PostCSS plugin"}),(0,s.jsx)("p",{children:"Installing Tailwind CSS as a PostCSS plugin is the most seamless way to integrate it with build tools like webpack, Rollup, Vite, and Parcel."})]}),(0,s.jsx)(o.R,{level:4,steps:r,code:i}),(0,s.jsx)(a._,{label:"Explore our framework guides",href:"/docs/installation/framework-guides",description:(0,s.jsxs)(s.Fragment,{children:[(0,s.jsx)("strong",{className:"font-semibold text-slate-900 dark:text-slate-200",children:"Are you stuck?"})," ","Setting up Tailwind with PostCSS can be a bit different across different build tools. Check our framework guides to see if we have more specific instructions for your particular setup."]})})]})}c.layoutProps={meta:{title:"Install Tailwind CSS using PostCSS",description:"Installing Tailwind CSS as a PostCSS plugin is the most seamless way to integrate it with build tools like webpack, Rollup, Vite, and Parcel.",section:"Getting Started"},Layout:l.L,allowOverflow:!1}}},function(e){e.O(0,[9495,7308,7667,5104,9774,2888,179],function(){return e(e.s=13477)}),_N_E=e.O()}]);